version: "3.8"

services:
  redis:
    image: redis:7
    restart: unless-stopped
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - d:\xml_data:/personal_app/xml_data
    depends_on:
      - celery

  celery:
    restart: unless-stopped
    build:
      context: .
    command: celery -A tasks:celery_app worker -B -l info
    volumes:
      - d:\xml_data:/personal_app/xml_data
    depends_on:
      - redis

  flower:
    restart: unless-stopped
    build:
      context: .
    command: celery -A tasks:celery_app flower
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

# docker-compose up -d --build
# docker-compose build
# docker-compose up -d



