version: "3.8"


services:
#  db: # подключение к БД происходит через 'host.docker.internal' на внешнюю, существующую БД

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    container_name: personal_app
    restart: unless-stopped
    ports:
      - 5001:5001

  celery:
    container_name: celery_app
    build:
      context: .
    command: ["/personal_app/docker/celery.sh"]
    depends_on:
      - redis

  flower:
    container_name: flower_app
    build:
      context: .
    command: celery -A tasks:celery_app flower
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555


# docker-compose build
# docker-compose up

