"""empty message

Revision ID: 196f0ee9f44b
Revises: c2c172757eca
Create Date: 2024-06-06 09:39:37.438409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '196f0ee9f44b'
down_revision: Union[str, None] = 'c2c172757eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('employee_test', sa.Column('KVL', sa.Float(), nullable=True))
    op.add_column('employee_test', sa.Column('division_1C', sa.String(length=255), nullable=True))
    op.add_column('employee_test', sa.Column('schedule_1C', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_test', 'schedule_1C')
    op.drop_column('employee_test', 'division_1C')
    op.drop_column('employee_test', 'KVL')
