"""empty message

Revision ID: a08b774a8876
Revises: 0500fcd98025
Create Date: 2024-06-03 11:03:40.197010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a08b774a8876'
down_revision: Union[str, None] = '0500fcd98025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('timesheet_test', 'skud_day_duration',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_test', 'skud_night_duration',
               existing_type=sa.SMALLINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('timesheet_test', 'late_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheet_test', 'late_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('timesheet_test', 'skud_night_duration',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('timesheet_test', 'skud_day_duration',
               existing_type=sa.Float(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
