"""empty message

Revision ID: c2c172757eca
Revises: e0892994596b
Create Date: 2024-06-04 14:08:37.007080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2c172757eca'
down_revision: Union[str, None] = 'e0892994596b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('timesheet_test', 'day_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=True)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheet_test', 'day_status',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
