"""empty message

Revision ID: c9ce9aa277d1
Revises: 8a2d2532ebbe
Create Date: 2024-06-10 11:21:34.313397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ce9aa277d1'
down_revision: Union[str, None] = '8a2d2532ebbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('day_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_days_id'), 'calendar_days', ['id'], unique=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_days_id'), table_name='calendar_days')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###
