"""empty message

Revision ID: d42878f753f7
Revises: 
Create Date: 2024-05-02 11:10:52.917177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42878f753f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_test',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employment_date', sa.DateTime(), nullable=True),
    sa.Column('fired_date', sa.DateTime(), nullable=True),
    sa.Column('birthday_date', sa.DateTime(), nullable=True),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('rank_title', sa.SmallInteger(), nullable=True),
    sa.Column('tabel_number', sa.String(length=30), nullable=True),
    sa.Column('tabel_filename', sa.String(length=255), nullable=True),
    sa.Column('tariff_rate', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('shift_hours', sa.SmallInteger(), nullable=True),
    sa.Column('skud_access', sa.SmallInteger(), nullable=True),
    sa.Column('day_start', sa.SmallInteger(), nullable=True),
    sa.Column('boss', sa.String(length=255), nullable=True),
    sa.Column('KTR_category', sa.String(length=50), nullable=True),
    sa.Column('KTR', sa.Float(), nullable=True),
    sa.Column('has_NAX', sa.Boolean(), nullable=True),
    sa.Column('KNAX', sa.Float(), nullable=True),
    sa.Column('fio_responsible', sa.String(), nullable=True),
    sa.Column('INN_employee', sa.String(length=50), nullable=True),
    sa.Column('INN_responsible', sa.String(length=50), nullable=True),
    sa.Column('INN_company', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'use_autogenerate': True}
    )
    op.create_table('timesheet_test',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('new_test_field_2', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('day_status', sa.String(length=10), nullable=True),
    sa.Column('skud_day_start_1', sa.DateTime(), nullable=True),
    sa.Column('skud_day_end_1', sa.DateTime(), nullable=True),
    sa.Column('skud_day_duration', sa.SmallInteger(), nullable=True),
    sa.Column('skud_night_duration', sa.SmallInteger(), nullable=True),
    sa.Column('is_day_alter', sa.Boolean(), nullable=True),
    sa.Column('altered_day_duration', sa.SmallInteger(), nullable=True),
    sa.Column('altered_night_duration', sa.SmallInteger(), nullable=True),
    sa.Column('is_night_alter', sa.Boolean(), nullable=True),
    sa.Column('skud_error', sa.Boolean(), nullable=True),
    sa.Column('skud_error_query', sa.String(), nullable=True),
    sa.Column('new_test_field', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'use_autogenerate': True}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet_test')
    op.drop_table('employee_test')
    # ### end Alembic commands ###
