"""empty message

Revision ID: e0892994596b
Revises: a08b774a8876
Create Date: 2024-06-04 14:02:06.777205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0892994596b'
down_revision: Union[str, None] = 'a08b774a8876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('timesheet_test', sa.Column('day_status_short', sa.String(length=10), nullable=True))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet_test', 'day_status_short')
