"""empty message

Revision ID: ea1bc8f92bc7
Revises: 1291959c6d17
Create Date: 2024-05-02 11:40:00.072487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea1bc8f92bc7'
down_revision: Union[str, None] = '1291959c6d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_test', 'new_field')
    op.drop_column('timesheet_test', 'new_test_field_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheet_test', sa.Column('new_test_field_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_test', sa.Column('new_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
