"""empty message

Revision ID: fe91bbcf22ad
Revises: f06066324904
Create Date: 2024-06-20 10:49:57.538149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe91bbcf22ad'
down_revision: Union[str, None] = 'f06066324904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsible_id'), 'responsible', ['id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_responsible_id'), table_name='responsible')
    op.drop_table('responsible')
    # ### end Alembic commands ###
