# Generated by Django 4.2.6 on 2023-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='symbol',
            field=models.CharField(max_length=2, unique=True, verbose_name='Статус'),
        ),
    ]
