# Generated by Django 4.2.6 on 2023-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_day_end_2',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_day_start_2',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_night_end_1',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_night_end_2',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_night_start_1',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_night_start_2',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_day_end_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_day_start_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вход'),
        ),
    ]
