# Generated by Django 4.2.6 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_remove_timesheet_skud_day_end_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='skud_error',
            field=models.BooleanField(default=False, verbose_name='Ошибка входа/выхода по данным СКУД'),
        ),
    ]
