# Generated by Django 4.2.6 on 2023-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_daystatus_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='KTR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Коэффициент тарифной ставки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='KTR_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория тарифной ставки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='boss',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='day_start',
            field=models.TimeField(verbose_name='Плановое время начала рабочего дня'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_NAX',
            field=models.BooleanField(default=False, verbose_name='Наличие НАКС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='schedule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
