# Generated by Django 4.2.6 on 2023-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_skud_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='skud_error_query',
            field=models.TextField(blank=True, null=True, verbose_name='Запрос на детализацию в БД СКУД'),
        ),
    ]
