# Generated by Django 4.2.6 on 2023-11-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_alter_employee_options_alter_employee_fio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('fio', 'date')},
        ),
    ]
