# Generated by Django 4.2.6 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_alter_timesheet_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_day_end',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='skud_day_start',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='skud_day_end_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание дневной смены  по СКУД (интервал 1)'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='skud_day_end_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание дневной смены  по СКУД (интервал 2)'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='skud_day_start_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало дневной смены по СКУД (интервал 1)'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='skud_day_start_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало дневной смены по СКУД (интервал 2)'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='boss_day_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность дневной смены по данным руководителя'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='boss_night_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность ночной смены по данным руководителя'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_day_corrected',
            field=models.BooleanField(default=False, verbose_name='Выполнена корректировка дневной смены'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_night_corrected',
            field=models.BooleanField(default=False, verbose_name='Выполнена корректировка ночной смены'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_day_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность дневной смены по СКУД'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_night_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длительность ночной смены по СКУД'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_night_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание ночной смены по СКУД'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='skud_night_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало ночной смены по СКУД'),
        ),
    ]
